// packages/svelte-site/src/components/embeds/BlueskyProfileFeed.svelte
<script lang="ts">
	import { type ProfileFeedData, renderProfileFeed } from 'bluesky-profile-feed-embed/core';
	import 'bluesky-profile-feed-embed/style.css';

	interface Props {
		data: ProfileFeedData;
	}

	let { data }: Props = $props();
</script>

<bluesky-profile-feed actor={data.profile?.did}>{@html renderProfileFeed(data)}</bluesky-profile-feed>

// packages/site/src/components/bluesky-profile-feed.tsx
import { useMemo } from 'preact/hooks';

import { renderProfileFeed, type ProfileFeedData } from 'bluesky-profile-feed-embed/core';
import 'bluesky-profile-feed-embed/style.css';

const BlueskyProfileFeed = ({ data }: { data: ProfileFeedData }) => {
	const html = useMemo(() => renderProfileFeed(data), [data]);

	return (
		<bluesky-profile-feed
			actor={data.profile?.did}
			dangerouslySetInnerHTML={{ __html: html }}
		></bluesky-profile-feed>
	);
};

export default BlueskyProfileFeed;

declare module 'preact' {
	namespace JSX {
		interface BlueskyProfileFeedAttributes extends HTMLAttributes<HTMLElement> {
			actor?: string;
		}

		interface IntrinsicElements {
			'bluesky-profile-feed': BlueskyProfileFeedAttributes;
		}
	}
}
